/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 6.1 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import pt.up.fe.comp.jmm.JmmNode;

import java.lang.RuntimeException;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

public
class SimpleNode implements Node, JmmNode {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected Grammar parser;
  protected Map<String, String> attrs;

  // added
    public int val;

  public SimpleNode(int i) {
    id = i;
    attrs = new HashMap<>();
  }

  public SimpleNode(Grammar p, int i) {
    this(i);
    parser = p;
  }


  public String getKind() {
	  return toString();
  }

  // TODO: implement.
  public List<String> getAttributes() {
    /*for ( String key : team1.keySet() ) {
	List<String> a = new ArrayList<>();
	String asd = new String("blah");
	a.add(asd);
	return a;
    //throw new RuntimeException("Not implemented yet");*/
    return new ArrayList<>(attrs.keySet());
  }

  // TODO: implement.
  public void put(String attribute, String value) {
    attrs.put(attribute, value);
	//throw new RuntimeException("Not implemented yet");
  }

  // TODO: implement.
  public String get(String attribute) {
	return attrs.get(attribute);
    //throw new RuntimeException("Not implemented yet");
  }
  
  public List<JmmNode> getChildren() {
    return JmmNode.convertChildren(children);
  }
  
  public int getNumChildren() {
    return jjtGetNumChildren();
  }
  
  public void add(JmmNode child, int index) {
    if(!(child instanceof Node)) {
  	throw new RuntimeException("Node not supported: " + child.getClass());  
    }
	  
	jjtAddChild((Node) child, index);
  }


  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  // TODO: print the type.
  public String toString() {
    return GrammarTreeConstants.jjtNodeName[id];
  }
  public String toString(String prefix) {
    String temp = "";
    if (this.getAttributes().size() == 0){
      return prefix + toString();
    }

    for (String attr : this.getAttributes()) {
      if(!attr.equals("line") && !attr.equals("col")){
        temp += this.get(attr) + " ";
      }
    }
    return prefix + toString() + " :: " + temp;
  }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
    System.out.println(toString(prefix));
    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + " ");
        }
      }
    }
  }

  public int getId() {
    return id;
  }
}

/* JavaCC - OriginalChecksum=d33fdb2b8063d5de3474649324d5d160 (do not edit this line) */
